- id: primary-standalone-haproxy
  type: group
  role: [primary-standalone-haproxy]
  requires: [deploy_start]
  required_for: [deploy_end, standalone-haproxy, primary-controller]
  parameters:
    strategy:
      type: parallel
  tasks:
    - hiera
    - fuel_pkgs
    - globals
    - tools
    - logging
    - hiera_default_route
    - netconfig
    - hosts
    - primary-cluster-haproxy
    - openstack-haproxy-ceilometer
    - openstack-haproxy-nova
    - openstack-haproxy-sahara
    - openstack-haproxy-glance
    - openstack-haproxy-heat
    - openstack-haproxy-cinder
    - openstack-haproxy-keystone
    - openstack-haproxy-murano
    - openstack-haproxy-horizon
    - openstack-haproxy-stats
    - openstack-haproxy-ironic
    - openstack-haproxy-radosgw
    - openstack-haproxy-swift
    - openstack-haproxy-neutron
    - openstack-haproxy-mysqld
    - openstack-haproxy-aodh
    - openstack-haproxy
    - ssl-keys-saving
    - ssl-add-trust-chain

- id: standalone-haproxy
  type: group
  role: [standalone-haproxy]
  requires: [deploy_start]
  required_for: [deploy_end, primary-controller]
  parameters:
    strategy:
      type: parallel
  tasks:
    - hiera
    - fuel_pkgs
    - globals
    - tools
    - logging
    - hiera_default_route
    - netconfig
    - hosts
    - cluster-haproxy
    - openstack-haproxy-ceilometer
    - openstack-haproxy-nova
    - openstack-haproxy-sahara
    - openstack-haproxy-glance
    - openstack-haproxy-heat
    - openstack-haproxy-cinder
    - openstack-haproxy-keystone
    - openstack-haproxy-murano
    - openstack-haproxy-horizon
    - openstack-haproxy-stats
    - openstack-haproxy-ironic
    - openstack-haproxy-radosgw
    - openstack-haproxy-swift
    - openstack-haproxy-neutron
    - openstack-haproxy-mysqld
    - openstack-haproxy-aodh
    - openstack-haproxy
    - ssl-keys-saving
    - ssl-add-trust-chain

- id: standalone-haproxy-hiera
  version: 2.0.0
  type: puppet
  groups: ['/.*/']
  requires: [hiera]
  required_for: [standalone-haproxy-hiera-update]
  parameters:
    puppet_manifest: puppet/manifests/add_to_hiera.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 120

- id: standalone-haproxy-hiera-update
  version: 2.0.0
  type: puppet
  groups: ['/.*/']
  requires: [standalone-haproxy-hiera]
  required_for: [globals]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/hiera/hiera.pp
    puppet_modules: /etc/puppet/modules
    timeout: 360

- id: standalone-haproxy-mysqld-status
  version: 2.0.0
  type: puppet
  groups: [primary-standalone-haproxy, standalone-haproxy]
  requires: [deploy_start, cluster-haproxy]
  required_for: [openstack-haproxy, deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/openstack-haproxy-mysqld-status.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 180

- id: standalone-haproxy-settings
  version: 2.0.0
  type: puppet
  groups: [primary-standalone-haproxy, standalone-haproxy]
  requires: [deploy_start, hosts]
  required_for: [standalone-haproxy-cluster, deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/settings.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 180

- id: primary-standalone-haproxy-cluster
  type: puppet
  version: 2.0.0
  groups: [primary-standalone-haproxy]
  required_for: [deploy_end, primary-cluster-haproxy]
  requires: [hosts, firewall, deploy_start]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/cluster/cluster.pp
    puppet_modules: /etc/puppet/modules
    timeout: 300

- id: standalone-haproxy-cluster
  type: puppet
  version: 2.0.0
  groups: [standalone-haproxy]
  cross-depends:
    - name: primary-standalone-haproxy-cluster
      role: primary-standalone-haproxy
  required_for: [deploy_end, cluster-haproxy]
  requires: [hosts, firewall, deploy_start]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/cluster/cluster.pp
    puppet_modules: /etc/puppet/modules
    timeout: 300

- id: standalone-haproxy-virtual_ips
  type: puppet
  version: 2.0.0
  groups: [primary-standalone-haproxy, standalone-haproxy]
  required_for: [deploy_end, primary-cluster-haproxy, cluster-haproxy]
  requires: [primary-standalone-haproxy-cluster, standalone-haproxy-cluster]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/virtual_ips/virtual_ips.pp
    puppet_modules: /etc/puppet/modules
    timeout: 180

